#!/usr/bin/env bash
export PLUGIN_COMMAND_PREFIX="library"
export PLUGIN_SERVICE="library"
export PLUGIN_DATA_ROOT="${DOKKU_LIB_ROOT:-/var/lib/dokku}/services/library"
export DOKKU_BIN="${DOKKU_BIN:-/usr/bin/dokku}"
PLUGIN_BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PLUGIN_BASE_PATH
