library:
  description: Open-source monitoring and observability platform
  url: https://grafana.com
  prompts:
    - key: DOMAIN
      question: Domain for Grafana
      default: grafana.%HOSTNAME%
  connection_env:
    service: db
    type: postgres
    mode: map
    map:
      host_port: GF_DATABASE_HOST
      user: GF_DATABASE_USER
      password: GF_DATABASE_PASSWORD
      name: GF_DATABASE_NAME

services:
  db:
    type: postgres

apps:
  grafana:
    image: grafana/grafana:latest
    domains: ["%DOMAIN%"]
    links:
      postgres: db
    env:
      GF_SERVER_ROOT_URL: "http://%DOMAIN%"
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_SSL_MODE: disable
      GF_SECURITY_ADMIN_PASSWORD: "%SECRET%"
    sso_env:
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "Remote-User"
      GF_AUTH_PROXY_HEADER_PROPERTY: "username"
      GF_AUTH_PROXY_HEADERS: "Email:Remote-Email Name:Remote-Name"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN: "true"
    ports:
      http: "80:3000"
    letsencrypt: true
    healthchecks:
      web:
        - path: /api/health
          timeout: 60
